"""add_crew_management_and_production_fields

Revision ID: 199caa545697
Revises: a39e9f58f0da
Create Date: 2025-12-30 12:48:44.957427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199caa545697'
down_revision: Union[str, Sequence[str], None] = 'a39e9f58f0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_crew_id'), 'production_crew', ['id'], unique=False)
    op.add_column('productions', sa.Column('locations', sa.String(), nullable=True))
    op.add_column('productions', sa.Column('filming_dates', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productions', 'filming_dates')
    op.drop_column('productions', 'locations')
    op.drop_index(op.f('ix_production_crew_id'), table_name='production_crew')
    op.drop_table('production_crew')
    # ### end Alembic commands ###
