"""add_fiscal_and_payment_fields

Revision ID: 69f94d59d51c
Revises: 199caa545697
Create Date: 2025-12-30 22:45:54.058745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f94d59d51c'
down_revision: Union[str, Sequence[str], None] = '199caa545697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('cnpj', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('address', sa.String(), nullable=True))
    op.add_column('productions', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('productions', sa.Column('payment_status', sa.String(), nullable=False, server_default='pending'))
    op.add_column('productions', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productions', 'due_date')
    op.drop_column('productions', 'payment_status')
    op.drop_column('productions', 'payment_method')
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'cnpj')
    # ### end Alembic commands ###
