"""Add production items and financial fields

Revision ID: 72d6f82448f7
Revises: 0d726d6008b3
Create Date: 2025-12-29 17:40:25.181972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d6f82448f7'
down_revision: Union[str, Sequence[str], None] = '0d726d6008b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_items_id'), 'production_items', ['id'], unique=False)
    # Add columns as nullable first
    op.add_column('productions', sa.Column('subtotal', sa.Integer(), nullable=True))
    op.add_column('productions', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('productions', sa.Column('tax_rate', sa.Float(), nullable=True))
    op.add_column('productions', sa.Column('tax_amount', sa.Integer(), nullable=True))
    op.add_column('productions', sa.Column('total_value', sa.Integer(), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE productions SET subtotal = 0 WHERE subtotal IS NULL")
    op.execute("UPDATE productions SET discount = 0 WHERE discount IS NULL")
    op.execute("UPDATE productions SET tax_rate = 0.0 WHERE tax_rate IS NULL")
    op.execute("UPDATE productions SET tax_amount = 0 WHERE tax_amount IS NULL")
    op.execute("UPDATE productions SET total_value = 0 WHERE total_value IS NULL")

    # Alter columns to NOT NULL
    op.alter_column('productions', 'subtotal', nullable=False)
    op.alter_column('productions', 'discount', nullable=False)
    op.alter_column('productions', 'tax_rate', nullable=False)
    op.alter_column('productions', 'tax_amount', nullable=False)
    op.alter_column('productions', 'total_value', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productions', 'total_value')
    op.drop_column('productions', 'tax_amount')
    op.drop_column('productions', 'tax_rate')
    op.drop_column('productions', 'discount')
    op.drop_column('productions', 'subtotal')
    op.drop_index(op.f('ix_production_items_id'), table_name='production_items')
    op.drop_table('production_items')
    # ### end Alembic commands ###
