"""add_service_id_to_production_items

Revision ID: a39e9f58f0da
Revises: f61dcb264113
Create Date: 2025-12-30 11:11:51.497645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39e9f58f0da'
down_revision: Union[str, Sequence[str], None] = 'f61dcb264113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_items', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'production_items', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'production_items', type_='foreignkey')
    op.drop_column('production_items', 'service_id')
    # ### end Alembic commands ###
