"""Add expenses table and profit fields

Revision ID: ba4cbaf59294
Revises: 72d6f82448f7
Create Date: 2025-12-29 18:31:24.347401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4cbaf59294'
down_revision: Union[str, Sequence[str], None] = '72d6f82448f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('paid_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    # Add columns as nullable first
    op.add_column('productions', sa.Column('total_cost', sa.Integer(), nullable=True))
    op.add_column('productions', sa.Column('profit', sa.Integer(), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE productions SET total_cost = 0 WHERE total_cost IS NULL")
    op.execute("UPDATE productions SET profit = 0 WHERE profit IS NULL")

    # Alter columns to NOT NULL
    op.alter_column('productions', 'total_cost', nullable=False)
    op.alter_column('productions', 'profit', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productions', 'profit')
    op.drop_column('productions', 'total_cost')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
