"""add priority field to productions table

Revision ID: bbb2c5e6792e
Revises: 69f94d59d51c
Create Date: 2026-01-01 02:16:10.538597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb2c5e6792e'
down_revision: Union[str, Sequence[str], None] = '69f94d59d51c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productions', sa.Column('priority', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productions', 'priority')
    # ### end Alembic commands ###
