"""add_subscription_management_to_organizations

Revision ID: e73dc9201eac
Revises: bb4715090f61
Create Date: 2026-01-05 12:51:07.115285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e73dc9201eac'
down_revision: Union[str, Sequence[str], None] = 'bb4715090f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_expenses_production'), table_name='expenses')
    op.add_column('organizations', sa.Column('subscription_plan', sa.String(), nullable=False, server_default='free'))
    op.add_column('organizations', sa.Column('subscription_status', sa.String(), nullable=False, server_default='trialing'))
    op.add_column('organizations', sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
    op.add_column('organizations', sa.Column('subscription_ends_at', sa.DateTime(), nullable=True))
    op.add_column('organizations', sa.Column('billing_id', sa.String(), nullable=True))
    
    # Remove server defaults after setting them to keep schema clean
    op.execute("ALTER TABLE organizations ALTER COLUMN subscription_plan DROP DEFAULT")
    op.execute("ALTER TABLE organizations ALTER COLUMN subscription_status DROP DEFAULT")

    op.drop_index(op.f('idx_production_crew_prod_user'), table_name='production_crew')
    op.drop_index(op.f('idx_production_crew_production'), table_name='production_crew')
    op.drop_index(op.f('idx_production_crew_user'), table_name='production_crew')
    op.drop_index(op.f('idx_production_items_production'), table_name='production_items')
    op.alter_column('productions', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_productions_created_at'), table_name='productions')
    op.drop_index(op.f('idx_productions_deadline'), table_name='productions', postgresql_where='(deadline IS NOT NULL)')
    op.drop_index(op.f('idx_productions_org_status'), table_name='productions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_productions_org_status'), 'productions', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('idx_productions_deadline'), 'productions', ['deadline'], unique=False, postgresql_where='(deadline IS NOT NULL)')
    op.create_index(op.f('idx_productions_created_at'), 'productions', [sa.literal_column('created_at DESC')], unique=False)
    # op.alter_column('productions', 'notes',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    op.create_index(op.f('idx_production_items_production'), 'production_items', ['production_id'], unique=False)
    op.create_index(op.f('idx_production_crew_user'), 'production_crew', ['user_id'], unique=False)
    op.create_index(op.f('idx_production_crew_production'), 'production_crew', ['production_id'], unique=False)
    op.create_index(op.f('idx_production_crew_prod_user'), 'production_crew', ['production_id', 'user_id'], unique=False)
    op.drop_column('organizations', 'billing_id')
    op.drop_column('organizations', 'subscription_ends_at')
    op.drop_column('organizations', 'trial_ends_at')
    op.drop_column('organizations', 'subscription_status')
    op.drop_column('organizations', 'subscription_plan')
    op.create_index(op.f('idx_expenses_production'), 'expenses', ['production_id'], unique=False)
    # ### end Alembic commands ###
