"""Add organization contact fields and default tax rate

Revision ID: f61dcb264113
Revises: ba4cbaf59294
Create Date: 2025-12-29 18:56:27.579868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61dcb264113'
down_revision: Union[str, Sequence[str], None] = 'ba4cbaf59294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('email', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('address', sa.String(), nullable=True))
    # Add columns as nullable first
    op.add_column('organizations', sa.Column('default_tax_rate', sa.Float(), nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE organizations SET default_tax_rate = 0.0 WHERE default_tax_rate IS NULL")

    # Alter column to NOT NULL
    op.alter_column('organizations', 'default_tax_rate', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'default_tax_rate')
    op.drop_column('organizations', 'address')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'phone')
    # ### end Alembic commands ###
